-- Learn T-SQL Querying
-- Chapter 10 - Tracking performance history with Query Store
-- Section - Introducing the Query Store

USE [master]
GO

ALTER DATABASE [AdventureWorks2016] 
SET QUERY_STORE = ON
GO

ALTER DATABASE [AdventureWorks2016] 
SET QUERY_STORE (OPERATION_MODE = READ_WRITE)
GO

USE [master]
GO
ALTER DATABASE [model] SET QUERY_STORE = ON
GO
ALTER DATABASE [model] SET QUERY_STORE (OPERATION_MODE = READ_WRITE)
GO

USE [master]
GO
ALTER DATABASE [AdventureWorks2016] SET QUERY_STORE = ON
GO
ALTER DATABASE [AdventureWorks2016] SET QUERY_STORE (
	OPERATION_MODE = READ_WRITE, 
	DATA_FLUSH_INTERVAL_SECONDS = 900,
	INTERVAL_LENGTH_MINUTES = 60,
	MAX_STORAGE_SIZE_MB = 1000, 
	QUERY_CAPTURE_MODE = AUTO,
	SIZE_BASED_CLEANUP_MODE = AUTO, 
	MAX_PLANS_PER_QUERY = 200,
	WAIT_STATS_CAPTURE_MODE = ON,
	CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 90)
	);

USE [master]
GO
ALTER DATABASE [AdventureWorks2016] SET QUERY_STORE = ON
GO
ALTER DATABASE [AdventureWorks2016] SET QUERY_STORE (
	OPERATION_MODE = READ_WRITE, 
	DATA_FLUSH_INTERVAL_SECONDS = 900,
	INTERVAL_LENGTH_MINUTES = 60,
	MAX_STORAGE_SIZE_MB = 1000, 
	QUERY_CAPTURE_MODE = CUSTOM,
	SIZE_BASED_CLEANUP_MODE = AUTO, 
	MAX_PLANS_PER_QUERY = 200,
	WAIT_STATS_CAPTURE_MODE = ON,
	CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 90),
	QUERY_CAPTURE_POLICY = (
		EXECUTION_COUNT = 30
		TOTAL_COMPILE_CPU_TIME_MS = 1000
		TOTAL_EXECUTION_CPU_TIME_MS = 100 
		)
	);


